In [2]:
if 5<2:
  print("5 > 2")
else:
  print("2>5")

2>5


In [3]:
print("How Are you ?")

How Are you ?


In [4]:
a=10
print(a)
print(type(a))

10
<class 'int'>


In [5]:
b=10.879879
print(b)
print(type(b))

10.879879
<class 'float'>


In [6]:
c=16j
print("Complex Number",c)
print(type(c))

Complex Number 16j
<class 'complex'>


In [7]:
N = "GOKUL"
print("My Name is ",N)
print(len(N))


My Name is  GOKUL
5


In [8]:
s= {1,2,3,4}
print(s)
print(len(s))
print(type(s))

{1, 2, 3, 4}
4
<class 'set'>


In [9]:
fs=frozenset({5,78,545,4,2})
print(fs)
print(type(fs))
print(len(fs))

frozenset({545, 2, 4, 5, 78})
<class 'frozenset'>
5


In [10]:
m = True
print(m)
print(type(m))

True
<class 'bool'>


In [11]:
by =b"Gokul"
print(by)
print(type(by))
print(len(by))

b'Gokul'
<class 'bytes'>
5


In [12]:
list =[0,65,454,5]
print(list)
print(type(list))
print(len(list))

[0, 65, 454, 5]
<class 'list'>
4


In [13]:
tuple = (5,2,7,2,8,5)
print(tuple)
print(len(tuple))
print(type(tuple))

(5, 2, 7, 2, 8, 5)
6
<class 'tuple'>


In [14]:
d = {"fruit":"Apple","Age" : 18}
print(d)
print(type(d))
print(len(d))

{'fruit': 'Apple', 'Age': 18}
<class 'dict'>
2


In [15]:
z= 10
y= 12
x = z+y
print(f"The sum is {x}")

The sum is 22


In [16]:
a= 10
d= 12
t = z-y
print(f"The difference is {t}")

The difference is -2


In [17]:
z=10
y=56
x=y*z
print(f"The Product is {x}")

The Product is 560


In [18]:
z=10
y=56
x=y%z
print(f"The Remainder is {x}")

The Remainder is 6


In [19]:
z=10
y=56
x=y//z
print(f"The quotient is {x}")

The quotient is 5


In [20]:
x=10
y=float(x)
c=str(x)
d=complex(x)
print(f"{y}\n{c}\n{d}\n")
print(type(x))

10.0
10
(10+0j)

<class 'int'>


In [21]:
string = "Gokul"
string_2 = "CSE"
print(len(string))
word = string[4]
print(word)
concatinate = string + string_2
print(concatinate)
Upper = string.upper()
print(Upper)

5
l
GokulCSE
GOKUL


In [23]:
try:
  N= int(input("Enter neumarator number : "))
  D = int(input("Enter denominator number : "))
  division = N/D
  print(division)
except:
  print("An Exception has Occurred")


Enter neumarator number : 7
Enter denominator number : 8
0.875


In [24]:
a = abs(-10)
b = abs(5/3)
print(b)

10
1.6666666666666667


In [25]:
print(bin(56))
print(bin(5))
print(bin(766))

0b111000
0b101
0b1011111110


In [26]:
print(dict(a='20',b='12'))

{'a': '20', 'b': '12'}


In [27]:

mylist = [10, 20, 30, 40, 50]
print(max(mylist))

print(max(24, 12, 36))

50
36


In [28]:
try:
  print(x)
except NameError:
  print("X is Not defined")
except:
  print("Some other error occured")

10


In [29]:
try:
  print(1/0)
except ZeroDivisionError:
  print("Zero Division Error Occurred")
except:
  print("Someother error occured")
else:
  print("No erroe occured")

Zero Division Error Occurred


In [30]:

def sum_of_two_numbers (a,b):
  sum = a + b
  print(f"The Sum of Two Number is : {sum}")

num1 = int(input("Enter a :"))
num2 = int(input("Enter b :"))
sum_of_two_numbers(num1,num2)


Enter a :45
Enter b :44
The Sum of Two Number is : 89


In [31]:
def square_a_number(a):
  square = a * a
  return square
square_number = int(input("Enter a:"))
print("The square of the given number is ",square_a_number(square_number))

Enter a:5
The square of the given number is  25


In [45]:
class Bike:
    name = ""
    gear = 0

bike1 = Bike()

bike1.gear = 6
bike1.name = "Mountain Bike"

print(f"Name: {bike1.name}, Gears: {bike1.gear} ")

Name: Mountain Bike, Gears: 6 


In [48]:
class Myclass:

  rollno = 0
Divith = Myclass()
Hari = Myclass()

Divith.rollno = 39
print(Divith.rollno)
Hari.rollno = 38
print(Hari.rollno)

39
38


In [49]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

car1 = Car("Toyota", "Camry")
car2 = Car("Tesla", "Model S")

print(car1.brand)
print(car2.brand)

Toyota
Tesla


In [38]:
class Car:
    wheels = 4

    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

car1 = Car("Toyota", "Camry")
car2 = Car("Tesla", "Model S")

print(car1.wheels)
print(car2.wheels)
Car.wheels = 6
print(car1.wheels)
print(car2.wheels)

4
4
6
6


In [57]:
#Linked List
class SinglyNode:
  def __init__(self,value,next =None):
    self.val = value
    self.next = next
  def __str__(self):
    return str(self.val)
Head = SinglyNode(1)
A = SinglyNode(3)
B = SinglyNode(7)
C = SinglyNode(8)

Head.next = A
A.next = B
B.next = C

In [60]:
curr = Head
while curr:
  print(curr.val)
  curr =  curr.next

1
3
7
8


In [62]:
a = [-3,-1,0,1,4,7]
def Binary_search(arr,target):
  N = len(arr)
  L = 0
  R = N-1

  while L <= R:
    M =(L + R)//2
    if arr[M] == target:
      return True
    elif target < arr[M] :
      R = M-1
    else:
      L = M+1

  return False

print(Binary_search(a,-2))

False


In [39]:
import numpy as np
a = np.array([[1,2,3],[3,5,6]])
print(a)
print([0]+[1])

[[1 2 3]
 [3 5 6]]
[0, 1]


In [40]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [41]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [42]:
import numpy as np
x = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(x.shape)
print(x.reshape(3,4))

(2, 2, 3)
[[ 1  2  3  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
